default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: myshop_development
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: myshop_test
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: <%= ENV['DATABASE_NAME']     %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME']     %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: <%= ENV['DATABASE_USER'] %>
  host:     <%= ENV['DATABASE_HOST'] %>
  port:     <%= ENV['DATABASE_PORT'] %>
